# Generated by Django 6.0.1 on 2026-01-27 08:34

import cloudinary.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden de Clasificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('service_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Edificación')),
                ('levels', models.CharField(blank=True, max_length=100, null=True, verbose_name='Niveles / Pisos')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Construida')),
                ('status', models.CharField(choices=[('en_proceso', 'En Ejecución'), ('entregado', 'Entregado')], default='en_proceso', max_length=50, verbose_name='Estado')),
                ('cover_image', cloudinary.models.CloudinaryField(help_text='Imagen cuadrada o vertical para el catálogo.', max_length=255, validators=[core.validators.MaxFileSizeValidator(limit_mb=5), core.validators.validate_image_extension], verbose_name='Imagen de Portada (Listado)')),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen panorámica ancha. Si se deja vacía, el frontend puede usar la portada como fallback.', max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=8), core.validators.validate_image_extension], verbose_name='Imagen de Banner (Detalle)')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='Información Extra (JSON)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Es Destacado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categories', models.ManyToManyField(related_name='projects', to='projects.category', verbose_name='Categorías')),
                ('related_projects', models.ManyToManyField(blank=True, help_text='Selecciona proyectos similares o etapas de la misma obra.', to='projects.project', verbose_name='Proyectos Relacionados')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['sort_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.MaxFileSizeValidator(limit_mb=5), core.validators.validate_image_extension], verbose_name='Imagen de Galería')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'db_table': 'project_images',
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título del Video')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.MaxFileSizeValidator(limit_mb=100), core.validators.validate_video_extension], verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Video de Proyecto',
                'verbose_name_plural': 'Videos de Proyectos',
                'db_table': 'project_videos',
            },
        ),
    ]
