# Generated by Django 6.0 on 2026-01-01 22:41

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug(URL)')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('service_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Edificación')),
                ('levels', models.CharField(blank=True, max_length=100, null=True, verbose_name='Niveles / Pisos')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área (m2)')),
                ('status', models.CharField(choices=[('en_proceso', 'En Ejecución'), ('entregado', 'Entregado')], default='en_proceso', max_length=50, verbose_name='Estado')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='Información Extra (JSON)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Es Destacado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.webp'])], verbose_name='Imagen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyectos',
                'db_table': 'project_images',
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='projects/videos/', validators=[core.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4', '.mov', '.avi', '.mkv'])], verbose_name='Video')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Video de Proyecto',
                'verbose_name_plural': 'Videos de Proyectos',
                'db_table': 'project_videos',
            },
        ),
    ]
