# Generated by Django 6.0.1 on 2026-01-28 04:10

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen cuadrada o vertical para el catálogo.', max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=5), core.validators.validate_image_extension], verbose_name='Imagen de Portada (Listado)'),
        ),
    ]
