# Generated by Django 6.0 on 2025-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'En Ejecución'), ('Delivered', 'Entregado')], default='Delivered', max_length=100),
        ),
    ]
