# Generated by Django 6.0 on 2026-01-02 23:31

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(upload_to='projects/videos/', validators=[core.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Video'),
        ),
    ]
