# Generated by Django 6.0 on 2026-01-24 21:35

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.category', verbose_name='Categorías'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen principal para el listado de proyectos.', null=True, upload_to='projects/covers/', verbose_name='Imagen de Portada (Principal)'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de Clasificación'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='poster',
            field=models.ImageField(blank=True, help_text='Imagen estática que se muestra antes de reproducir el video.', null=True, upload_to='projects/videos/posters/', verbose_name='Portada del Video (Poster)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(upload_to='projects/videos/', validators=[core.validators.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Video MP4'),
        ),
    ]
