# Generated by Django 6.0 on 2026-01-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_remove_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='poster',
        ),
    ]
