# Generated by Django 6.0 on 2026-01-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectvideo_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
