# Generated by Django 6.0 on 2025-12-27 03:52

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='¿Destacar en Inicio?'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/images/', validators=[projects.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(upload_to='projects/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv']), projects.models.validate_file_size]),
        ),
    ]
