# Generated by Django 6.0.1 on 2026-01-27 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('inquiry_type', models.CharField(choices=[('GENERAL', 'Consulta General'), ('QUOTE', 'Solicitud de Presupuesto'), ('PROJECT', 'Información de Proyecto'), ('SUPPLIER', 'Propuesta de Proveedor'), ('OTHER', 'Otro')], default='GENERAL', max_length=20, verbose_name='Tipo de Consulta')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('IN_PROGRESS', 'En Seguimiento'), ('REPLIED', 'Respondido/Cerrado'), ('SPAM', 'Spam')], default='NEW', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, help_text='Espacio para notas del equipo de ventas o administración.', verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
