# Generated by Django 6.0 on 2025-12-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='user_accounts',
        ),
    ]
