# Generated by Django 6.0.1 on 2026-01-27 07:33

import cloudinary.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la Empresa')),
                ('mission', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=5), core.validators.validate_image_extension], verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Nosotros (Misión/Visión)',
                'verbose_name_plural': 'Nosotros (Misión/Visión)',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.MaxFileSizeValidator(limit_mb=2), core.validators.validate_image_extension], verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client_logos',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('google_maps_url', models.URLField(blank=True, help_text='El enlace que va dentro del src del iframe', max_length=500, verbose_name='Link Iframe (Embed)')),
                ('google_maps_link', models.URLField(blank=True, help_text='El enlace corto para compartir', max_length=500, verbose_name='Link Compartir (Navegación)')),
                ('opening_hours', models.TextField(blank=True, help_text='Ej: Lunes a Viernes: 8 am - 5 pm', verbose_name='Horario de Atención')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('whatsapp', models.URLField(blank=True, default='', help_text='Número para link de WA', verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Información de Empresa',
                'verbose_name_plural': 'Información de Empresa',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Innovación y Solidez', max_length=100, verbose_name='Texto Superior')),
                ('title', models.CharField(default='Construimos', max_length=100, verbose_name='Título Principal')),
                ('highlight', models.CharField(default='El Futuro.', max_length=100, verbose_name='Texto Destacado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=10), core.validators.validate_image_extension], verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': 'Hero del Home',
                'verbose_name_plural': 'Hero del Home',
                'db_table': 'home_hero',
            },
        ),
        migrations.CreateModel(
            name='ProjectsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuestros', max_length=100, verbose_name='Título')),
                ('highlight', models.CharField(default='Proyectos.', max_length=100, verbose_name='Texto Destacado')),
                ('description', models.TextField(default='Una muestra de nuestra capacidad técnica...', verbose_name='Descripción')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=10), core.validators.validate_image_extension], verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': 'Banner de Proyectos',
                'verbose_name_plural': 'Banner de Proyectos',
                'db_table': 'projects_hero',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.MaxFileSizeValidator(limit_mb=5), core.validators.validate_image_extension], verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'services',
            },
        ),
    ]
