# Generated by Django 6.0 on 2026-01-01 22:42

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la Empresa')),
                ('mission', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/about/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.webp'])], verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Nosotros (Misión/Visión)',
                'verbose_name_plural': 'Nosotros (Misión/Visión)',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('image', models.ImageField(upload_to='company/clients/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.webp'])], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client_logos',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('google_maps_url', models.URLField(blank=True, help_text='Enlace directo a la ubicación', max_length=500, verbose_name='Link Google Maps')),
                ('opening_hours', models.TextField(blank=True, help_text='Ej: Lunes a Viernes: 8 am - 5 pm (Usa saltos de línea para separar días)', verbose_name='Horario de Atención')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('whatsapp', models.CharField(blank=True, help_text='Número para link de WA', max_length=50, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Información de Empresa',
                'verbose_name_plural': 'Información de Empresa',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/services/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.webp'])], verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'services',
            },
        ),
    ]
