# Generated by Django 6.0 on 2025-12-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la Empresa')),
                ('mission', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/about/', verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Nosotros (Misión/Visión)',
                'verbose_name_plural': 'Nosotros (Misión/Visión)',
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número para link de WA', max_length=50),
        ),
        migrations.AlterModelTable(
            name='companyinfo',
            table=None,
        ),
    ]
