# Generated by Django 6.0 on 2026-01-02 23:31

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company/about/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='image',
            field=models.ImageField(upload_to='company/clients/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram',
            field=models.URLField(blank=True, default='', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tiktok',
            field=models.URLField(blank=True, default='', verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.URLField(blank=True, default='', help_text='Número para link de WA', verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company/services/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen'),
        ),
    ]
