# Generated by Django 6.0 on 2025-12-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_aboutus_companyinfo_tiktok_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='image',
        ),
    ]
