# Generated by Django 6.0 on 2026-01-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_aboutus_image_alter_clientlogo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='El enlace corto (maps.app.goo.gl) para que el cliente navegue', max_length=500, verbose_name='Link Compartir (Navegación)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='El enlace que va dentro del src del iframe', max_length=500, verbose_name='Link Iframe (Embed)'),
        ),
    ]
