# Generated by Django 6.0 on 2026-01-24 18:35

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_clientlogo_created_at_service_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Innovación y Solidez', max_length=100, verbose_name='Texto Superior (Badge)')),
                ('title', models.CharField(default='Construimos', max_length=100, verbose_name='Título Principal')),
                ('highlight', models.CharField(default='El Futuro.', max_length=100, verbose_name='Texto Destacado (Gradiente)')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/home/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': 'Hero del Home',
                'verbose_name_plural': 'Hero del Home',
                'db_table': 'home_hero',
            },
        ),
    ]
