# Generated by Django 6.0 on 2026-01-24 23:35

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_homehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuestros', max_length=100, verbose_name='Título (Parte Blanca)')),
                ('highlight', models.CharField(default='Proyectos.', max_length=100, verbose_name='Texto Destacado (Naranja)')),
                ('description', models.TextField(default='Una muestra de nuestra capacidad técnica y visión arquitectónica. Cada obra refleja nuestro compromiso con la calidad.', verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/projects/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': 'Banner de Proyectos',
                'verbose_name_plural': 'Banner de Proyectos',
                'db_table': 'projects_hero',
            },
        ),
    ]
